### ISSUE TITLE
Problems with sub datasets in a jrxml file (ClassNotFoundExeception)

### ISSUE THREAD

**Issue by joggl71xpt** [quarkiverse/quarkus-jasperreports#166]
Using a simple jrxml file with a standart JSON Datasource works without any issues.
The project is setup like in the documentation and works without any issues even with resourcebundles(language files) with the 1.0.2 release inside an multistage docker container.

Using an report, which contains sub datasets leads to a ClassNotFoundException when filling the report.

it seems jasperreports creates some innerclasses for this kind of sub datasets and the current classloader is not able to find this class:

(FixedPriceGoAEInvoice.jrxml is the design file, containing the sub dataset "InvoicePositionsDataset")
Additional Notes: this kind of report works without any issues in DevMode, the problem happens only inside native Mode.

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: FixedPriceGoAEInvoice_InvoicePositionsDataset_4ffb55f9b3fdec22f0d1299da07c2208f610dc0af680922cf49a5a2163f2ed4f
	at net.sf.jasperreports.engine.util.JRClassLoader.loadClass(JRClassLoader.java:29)
	at net.sf.jasperreports.engine.util.CompiledClassesLoader.loadCompiledClass(CompiledClassesLoader.java:87)
	at net.sf.jasperreports.engine.util.JRClassLoader.loadClassFromBytes(JRClassLoader.java:286)
	at net.sf.jasperreports.engine.design.JRAbstractJavaCompiler.loadClass(JRAbstractJavaCompiler.java:168)
	at net.sf.jasperreports.engine.design.JRAbstractJavaCompiler.loadEvaluator(JRAbstractJavaCompiler.java:117)
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.createEvaluator(JRAbstractCompiler.java:459)
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.loadEvaluator(JRAbstractCompiler.java:427)
	at net.sf.jasperreports.engine.JasperCompileManager.getEvaluator(JasperCompileManager.java:374)
	at net.sf.jasperreports.engine.fill.JRFillDataset.createCalculator(JRFillDataset.java:526)
	at net.sf.jasperreports.engine.fill.JRFillDataset.createCalculator(JRFillDataset.java:516)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.createDatasets(BaseReportFiller.java:227)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:181)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:273)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:82)
	at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:252)
	at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:157)
	at net.sf.jasperreports.engine.JasperFillManager.fillFromRepo(JasperFillManager.java:671)
	.....
       <snip>
        ......
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
Caused by: java.lang.ClassNotFoundException: FixedPriceGoAEInvoice_InvoicePositionsDataset_4ffb55f9b3fdec22f0d1299da07c2208f610dc0af680922cf49a5a2163f2ed4f
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86)
	at java.base@21.0.5/java.lang.Class.forName(DynamicHub.java:1359)
	at java.base@21.0.5/java.lang.Class.forName(DynamicHub.java:1348)
	at net.sf.jasperreports.engine.util.JRClassLoader.loadClass(JRClassLoader.java:27)
	... 44 more
```

any ideas how to solve this ?

Thanx in advance

**Comment by melloware** [comment]
We currently have this integration test passing in Native for JSON Datasource but I have a feeling your scenario is more complex: https://github.com/quarkiverse/quarkus-jasperreports/blob/main/integration-tests/src/main/java/io/quarkiverse/jasperreports/it/JasperReportsJsonResource.java

**Comment by joggl71xpt** [comment]
I've created a full example here https://github.com/joggl71xpt/JasperQuarkusTest which shows the problem.
the code is completly stripped down to only contain the minium stuff needed. I hope it is understandable

Please see readme file for instructions how to build, run, test it

there are also some other issues I observed (also mentioned in the readme).
I'm working on a Mac M3 

there are 2 example files included, which contain `datasets`, but only the complex one fails with ClassNotFound ... at the moment I've no glue why. 

Idea: perhabs the root cause is a missing classfile for reflection and not the problem that the generated jasper file can't be loaded ?

BTW: I think in your quarkus-jasperreports the jasperreports-functions lib is missing... I've added it in my pom.xml separatly

**Comment by melloware** [comment]
awesome let me debug this and get back to you!  This is a huge help.

**Comment by joggl71xpt** [comment]
I think my assumption is correct, I just added in the TableDatasetReport table an additional column, displaying some simple date conversion (like in the complex example).  now this also fail... (I updated the example code).

**Comment by melloware** [comment]
i should be able to figure this out.

**Comment by melloware** [comment]
So in your TestDataTable report i see this `<property name="com.jaspersoft.studio.data.defaultdataadapter" value="SimpleJsonDataAdapter.jrdax"/>` but I don't see any SimpleJsonDataAdapter.jrdax file anywhere in your project?

**Comment by joggl71xpt** [comment]
yep, this is the "empty" Datasource Dataadapter to generate fields inside the Designer. I don't think that this is needed  during compiling... (I think it is only needed during design process to ease the generation of the model and to do the preview inside the designer)... but I can provide it to you if needed

**Comment by melloware** [comment]
No its OK i think i have a simpler example.

**Comment by melloware** [comment]
OK i deleted too much when moving to StoryBook 8.  Try 6.0.1

**Comment by melloware** [comment]
@joggl71xpt i just wrote an integration Test for your TableTest and it working for me locally letting the native build run now.

**Comment by melloware** [comment]
I am trying to get JasperReports to run on MacOS as part of my build: https://github.com/quarkiverse/quarkus-jasperreports/actions/runs/11785487564/job/32826842194

I set it up like POI extension which runs under MacOS but i am getting the following error. Any thoughts?

```
024-11-11 21:36:27,165 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /jasper/barcode4j/pdf failed, error id: a01d56b9-3cc7-4974-b698-574b9708f669-1: java.lang.UnsatisfiedLinkError: No awt in java.library.path
    at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136)
    at java.base@21.0.5/java.lang.ClassLoader.loadLibrary(ClassLoader.java:106)
    at java.base@21.0.5/java.lang.Runtime.loadLibrary0(Runtime.java:916)
    at java.base@21.0.5/java.lang.System.loadLibrary(System.java:2063)
    at java.desktop@21.0.5/java.awt.Toolkit$2.run(Toolkit.java:1384)
    at java.desktop@21.0.5/java.awt.Toolkit$2.run(Toolkit.java:1382)
    at java.base@21.0.5/java.security.AccessController.executePrivileged(AccessController.java:129)
    at java.base@21.0.5/java.security.AccessController.doPrivileged(AccessController.java:319)
    at java.desktop@21.0.5/java.awt.Toolkit.loadLibraries(Toolkit.java:1381)
    at java.desktop@21.0.5/java.awt.Toolkit.initStatic(Toolkit.java:1419)
    at java.desktop@21.0.5/java.awt.Toolkit.<clinit>(Toolkit.java:1393)
    at java.desktop@21.0.5/java.awt.Color.<clinit>(Color.java:277)
```

**Comment by melloware** [comment]
@joggl71xpt ok you can see from this PR i now have a `subdataset` integration test that passes on both Ubuntu and MacOS GRaalVM.

PR: https://github.com/quarkiverse/quarkus-jasperreports/pull/170

Build: https://github.com/quarkiverse/quarkus-jasperreports/actions/runs/11799642541

**Comment by melloware** [comment]
OK I have all your examples compiling and working on MacOS: https://github.com/quarkiverse/quarkus-jasperreports/pull/174

so not sure what your issue is?

**Comment by joggl71xpt** [comment]
first of all, thanx for your great work and help.
I found the root cause - but no solution
the problem is, if you have an expression for a field of an subdataset, than the above issue with the ClassNotFoundException of the sub dataset happens.

Example: the field $F{vatRate} is of type java.lang.Double

Following expression works:  
`<expression><![CDATA[$F{vatRate}]]></expression>`

but in the moment you add e.g. some calculation like: 
`<expression><![CDATA[$F{vatRate}/100.0]]></expression>`

than you will get an ClassNotFoundException

the same happens if you have e.g. an String field, which contains some date and you try to convert it to java.util.Date to do some formatting...this will also fail
If you do the same outside of an subdataset than it works...

As said, this problem only happens in native mode
At the moment I have no glue how to solve this...

**Comment by melloware** [comment]
I am testing your theory now i just changed an IT to do an expression / 100.0  https://github.com/quarkiverse/quarkus-jasperreports/pull/176

**Comment by melloware** [comment]
OK all tests pass on all Native builds https://github.com/quarkiverse/quarkus-jasperreports/actions/runs/11805342529 using `<expression><![CDATA[$F{grossAmount}/100.0]]></expression>`

SO I am not sure what your particular issue is.   Maybe start with our `integration-test` project instead of your own to see if that is the issue?

**Comment by joggl71xpt** [comment]
yep, I will try today...
